# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLG' do
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/AdMob'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Alamofire', '4.7.2'
  pod 'AlamofireImage', '3.3.1'
  pod 'PromiseKit', '4.4.0'
  pod 'ObjectMapper', '3.3.0'
  pod 'XCGLogger', '6.0.4'
  pod 'TPKeyboardAvoiding', '1.3.2'
 # pod 'Windless', '0.1.5'
  pod 'Crashlytics', '3.10.2'
  pod 'Fabric', '1.7.7'
 # pod 'FBSDKCoreKit'
#  pod 'FBSDKLoginKit'
#  pod 'GoogleSignIn', '4.1.2'
  pod 'GrowingTextView', '0.5.6'
 # pod 'Socket.IO-Client-Swift', '13.3.0'
  pod 'DGActivityIndicatorView', '2.1.1'
  pod 'FBAudienceNetwork'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'GoogleAnalytics'
 # pod 'GoogleMobileAdsMediationFacebook'
 # pod 'GoogleMobileAdsMediationInMobi'
  pod 'ScrollableSegmentedControl'
use_frameworks!

end
